spring.application.name=api_gateway

server.port=9090

spring.cloud.gateway.server.webmvc.routes[0].id=quiz-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://quiz-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/quiz/**

spring.cloud.gateway.server.webmvc.routes[1].id=question-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://question-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/question/**